apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: dummy-daemon
  template:
    metadata:
      labels:
        app: dummy-daemon
    spec:
      containers:
        - name: dummy-daemon-container
          image: nginx:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: dummy-config
            - secretRef:
                name: dummy-secret