apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-container
          image: nginx:latest
          envFrom:
            - configMapRef:
                name: dummy-config
            - secretRef:
                name: dummy-secret