apiVersion: v1
kind: Secret
metadata:
  name: dummy-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: "cGFzc3dvcmRTdXM0aEJyMAo="  # Base64 encoded 'password' change with encoded too. just dummy password