apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dummy-statefulset
  namespace: default
spec:
  serviceName: "dummy-service"
  replicas: 2
  selector:
    matchLabels:
      app: dummy-stateful
  template:
    metadata:
      labels:
        app: dummy-stateful
    spec:
      containers:
        - name: dummy-stateful-container
          image: nginx:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: dummy-config
            - secretRef:
                name: dummy-secret