# This rule is not used by the project config-reloader itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to operation.sendentembok.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: config-reloader
    app.kubernetes.io/managed-by: kustomize
  name: configreloader-viewer-role
rules:
- apiGroups:
  - operation.sendentembok.org
  resources:
  - configreloaders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operation.sendentembok.org
  resources:
  - configreloaders/status
  verbs:
  - get
