---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ops.nendeskombet.com
  resources:
  - configreloaders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.nendeskombet.com
  resources:
  - configreloaders/finalizers
  verbs:
  - update
- apiGroups:
  - ops.nendeskombet.com
  resources:
  - configreloaders/status
  verbs:
  - get
  - patch
  - update
