---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ops.nendeskombet.com
  resources:
  - configreloaders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.nendeskombet.com
  resources:
  - configreloaders/finalizers
  verbs:
  - update
- apiGroups:
  - ops.nendeskombet.com
  resources:
  - configreloaders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups: 
  - ops.nendeskombet.com
  resources: 
  - configreloaders
  verbs: 
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources: 
  - configmaps
  verbs:
  - get
  - list 
  - watch
